# Generated by Django 3.0.5 on 2020-05-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=200)),
                ('labid_text', models.CharField(max_length=9)),
                ('amount_text', models.CharField(max_length=200)),
                ('type_text', models.CharField(max_length=200)),
                ('location_text', models.CharField(max_length=200)),
            ],
        ),
    ]
