# Generated by Django 3.0.5 on 2020-10-19 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_text', models.CharField(max_length=20, verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_text', models.CharField(max_length=20, verbose_name='Type')),
            ],
        ),
        migrations.AlterField(
            model_name='paymententry',
            name='amount_text',
            field=models.CharField(max_length=200, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='paymententry',
            name='labid_text',
            field=models.CharField(max_length=9, verbose_name='Lab ID'),
        ),
        migrations.AlterField(
            model_name='paymententry',
            name='name_text',
            field=models.CharField(max_length=200, verbose_name='Patient Name'),
        ),
        migrations.AlterField(
            model_name='paymententry',
            name='location_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entryapp.Locations'),
        ),
        migrations.AlterField(
            model_name='paymententry',
            name='type_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entryapp.Types'),
        ),
    ]
