# Generated by Django 3.0.5 on 2020-10-19 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entryapp', '0002_auto_20201019_2105'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Locations',
            new_name='Location',
        ),
        migrations.RenameModel(
            old_name='Types',
            new_name='Type',
        ),
    ]
