# Generated by Django 3.0.5 on 2020-10-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entryapp', '0004_auto_20201019_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymententry',
            name='amount_text',
        ),
        migrations.AddField(
            model_name='paymententry',
            name='amount_double',
            field=models.FloatField(default=0, verbose_name='Amount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymententry',
            name='labid_text',
            field=models.CharField(max_length=9, verbose_name='Invoice Number'),
        ),
    ]
