# Generated by Django 3.0.5 on 2020-10-19 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entryapp', '0005_auto_20201019_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymententry',
            name='entry_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
