# Generated by Django 3.0.5 on 2020-10-20 01:51

from django.db import migrations, models
import entryapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('entryapp', '0006_paymententry_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymententry',
            name='receipt_number',
            field=models.CharField(default=entryapp.models.random_string, max_length=7),
        ),
        migrations.AddField(
            model_name='paymententry',
            name='staff_code',
            field=models.CharField(default='capxxx', max_length=7, verbose_name='Staff Code'),
        ),
    ]
