# Generated by Django 3.0.5 on 2020-10-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entryapp', '0007_auto_20201020_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymententry',
            name='amount_double',
        ),
        migrations.RemoveField(
            model_name='paymententry',
            name='type',
        ),
        migrations.AddField(
            model_name='paymententry',
            name='cash_amount',
            field=models.FloatField(default=0, verbose_name='Amount Paid by Cash'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymententry',
            name='cheque_amount',
            field=models.FloatField(default=0, verbose_name='Amount Paid by Cheque'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymententry',
            name='eftpos_amount',
            field=models.FloatField(default=0, verbose_name='Amount Paid by EFTPOS'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymententry',
            name='staff_code',
            field=models.CharField(max_length=7, verbose_name='Staff Code'),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
